version: '3.8'
name: marketdataprovider
services:
  redis:
    image: redis/redis-stack-server:latest
    ports: 
      - '6379:6379'
    # volumes:
    #   - /cache:/data
    environment:
      - WIPE_REDIS_ON_START=True
    networks:
      - marketviewer

  marketdataprovider-api:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - '3000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    env_file:
      - ./src/MarketDataProvider.Api/dev.env
    networks:
      - marketviewer
      
networks:
  marketviewer:
    name: marketviewer